import type { Tool } from '../api/image';

/**
 * Demo (guest) mode data. No backend / Replicate calls are made — guests pick
 * one of these sample images and see pre-baked before/after results.
 *
 * Images live in frontend/public/demo/. The "after" results were generated by
 * running each original through the real Replicate models once.
 */

export interface DemoSample {
  id: string;
  label: string;
  original: string;
  results: Record<Tool, string>;
}

export const DEMO_SAMPLES: DemoSample[] = [
  {
    id: 'portrait',
    label: 'Portrait',
    original: '/demo/portrait.jpeg',
    results: {
      'super-resolution': '/demo/portrait-super-resolution.png',
      'remove-noise': '/demo/portrait-remove-noise.png',
      'remove-background': '/demo/portrait-remove-background.png',
    },
  },
  {
    id: 'pet',
    label: 'Pet',
    original: '/demo/pet.jpeg',
    results: {
      'super-resolution': '/demo/pet-super-resolution.png',
      'remove-noise': '/demo/pet-remove-noise.png',
      'remove-background': '/demo/pet-remove-background.png',
    },
  },
  {
    id: 'car',
    label: 'Car',
    original: '/demo/product.jpg',
    results: {
      'super-resolution': '/demo/product-super-resolution.png',
      'remove-noise': '/demo/product-remove-noise.png',
      'remove-background': '/demo/product-remove-background.png',
    },
  },
];
